apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - service.yaml
  - ingress.yaml
  - alert.yaml
patches:
  - path: otel-env-patch.yaml
replacements:
  - source:
      kind: Deployment
      name: kuberneteswrapper
      fieldPath: metadata.annotations.[altinn.studio/image]
    targets:
      - select:
          kind: Deployment
          name: kuberneteswrapper
        fieldPaths:
          - spec.template.spec.containers.[name=kuberneteswrapper].image
