apiVersion: v1
kind: Service
metadata:
  name: kuberneteswrapper
  labels:
    app: kuberneteswrapper
    release: kuberneteswrapper
spec:
  ports:
    - port: 3000
      targetPort: 8080
      protocol: TCP
      name: kuberneteswrapper
  selector:
    app: kuberneteswrapper
    release: kuberneteswrapper
