apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../overlay
patches:
  - target:
      kind: IngressRoute
      name: kuberneteswrapper-ingress-route
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`${SERVICEOWNER_ID}.apps.tt02.altinn.no`)&&PathPrefix(`/kuberneteswrapper`)
