apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../overlay
patches:
  - target:
      kind: Ingress
      name: kuberneteswrapper-base-path
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.altinn.studio
