name: App Backend - Verify formatting

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/App/backend/**'
      - '.github/workflows/app-backend-formatting.yml'

jobs:
  verify-no-changes:
    if: |
      github.event.pull_request.user.login != 'renovate[bot]'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/App/backend/

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup .NET
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
        with:
          global-json-file: src/App/backend/global.json
      - name: Install csharpier
        run: dotnet tool restore
      - name: Run csharpier
        run: dotnet csharpier check .
