name: Deploy studio syncroot

on:
  push:
    branches:
      - main
    paths:
      - infra/studio/syncroot/**
      - .github/workflows/deploy-studio-syncroot.yaml
  workflow_dispatch:
    inputs:
      environments:
        description: 'Environments to deploy to. Multiple environments can be specified by separating them with a comma.'
        required: false
        default: 'dev'

permissions:
  id-token: write
  contents: read

jobs:
  get-short-sha:
    uses: ./.github/workflows/template-short-sha.yaml

  construct-environments-array:
    uses: ./.github/workflows/template-studio-construct-environments.yaml
    with:
      inputs: ${{ toJSON(github.event.inputs) }}

  push-syncroot-artifact:
    name: Push syncroot as OCI artifact
    needs: [get-short-sha]
    runs-on: ubuntu-latest
    environment: dev
    env:
      REGISTRY_NAME: altinntjenestercontainerregistry
      CONFIG_REPO: altinntjenestercontainerregistry.azurecr.io/configs/studio-syncroot:${{ needs.get-short-sha.outputs.short-sha }}
      SYNCROOT_RELEASE_DIRECTORY: syncroot-release
    outputs:
      CONFIG_REPO: altinntjenestercontainerregistry.azurecr.io/configs/studio-syncroot:${{ needs.get-short-sha.outputs.short-sha }}
    defaults:
      run:
        working-directory: ./infra/studio
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: az login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_FC }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_FC }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_FC }}

      - name: az acr login
        run: az acr login --name ${{ env.REGISTRY_NAME }}

      - name: flux install
        uses: fluxcd/flux2/action@8454b02a32e48d775b9f563cb51fdcb1787b5b93 # v2.7.5

      - name: filter yaml files to release directory (exclude README.md etc)
        run: |
          rsync -av --include='*/' --include='*.yaml' --include='*.yml' --exclude='*' syncroot/ ${{ env.SYNCROOT_RELEASE_DIRECTORY }}/

      - name: push artifact
        run: |
          flux push artifact oci://${{ env.CONFIG_REPO }} \
            --provider=generic \
            --reproducible \
            --path="${{ env.SYNCROOT_RELEASE_DIRECTORY }}" \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)/$(git rev-parse HEAD)"

  tag-syncroot:
    name: Tag syncroot
    needs: [push-syncroot-artifact, construct-environments-array]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    env:
      REGISTRY_NAME: altinntjenestercontainerregistry
    strategy:
      matrix:
        include: ${{ fromJSON(needs.construct-environments-array.outputs.result) }}
    steps:
      - name: az login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_FC }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_FC }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_FC }}

      - name: az acr login
        run: az acr login --name ${{ env.REGISTRY_NAME }}

      - name: flux install
        uses: fluxcd/flux2/action@8454b02a32e48d775b9f563cb51fdcb1787b5b93 # v2.7.5

      - name: tag artifact
        run: |
          flux tag artifact oci://${{ needs.push-syncroot-artifact.outputs.CONFIG_REPO }} \
            --tag ${{ matrix.environment }}
