name: Designer Backend - Gitea and Db integration tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/Designer/backend/**'
      - 'src/Designer/testdata/**'
      - 'src/gitea/**'
      - '.github/workflows/designer-backend-gitea-and-db-integration-tests.yaml'
  workflow_dispatch:

jobs:
  gitea-and-db-integration-tests:
    name: Run integration tests against actual gitea and dbs
    runs-on: ubuntu-latest
    env:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
        with:
          dotnet-version: |
            9.0.x
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build
        run: |
           dotnet build backend/Designer.sln -v m
        working-directory: src/Designer

      - name: Run integration tests
        run: |
           dotnet test backend/Designer.sln --filter "(Category=GiteaIntegrationTest)|(Category=DbIntegrationTest)" -v m
        working-directory: src/Designer
