name: Designer Frontend - Playwright tests on PR

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/Designer/frontend/**'
      - '!src/Designer/frontend/admin/**'
      - '!src/Designer/frontend/stats/**'
      - 'src/Designer/backend/**'
      - '.github/workflows/designer-frontend-run-playwright-on-pr.yaml'
      - 'src/Designer/compose.yaml'
      - 'src/Designer/Dockerfile'
      - 'src/gitea/**'
      - 'package.json'
      - 'src/Designer/development/**'
      - 'src/App/template/**'
      - 'yarn.lock'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright-tests:
    name: Build environment and run e2e test
    timeout-minutes: 25
    runs-on: ubuntu-latest

    steps:
      - name: 'Checking Out Code'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Generate .env file
        run: |
          echo PLAYWRIGHT_TEST_APP=autodeploy-v3 >> .env
          echo DEVELOP_APP_DEVELOPMENT=0 >> .env
          echo DEVELOP_RESOURCE_ADMIN=0 >> .env
          echo DEVELOP_BACKEND=0 >> .env
          echo DEVELOP_DASHBOARD=0 >> .env
          echo DEVELOP_PREVIEW=0 >> .env
          echo GITEA_ADMIN_PASS=g9wDIG@6gf >> .env
          echo GITEA_ADMIN_USER=localg1iteaadmin >> .env
          echo GITEA_CYPRESS_USER=cypress_testuser >> .env
          echo GITEA_CYPRESS_PASS=g9wDIG@6gf >> .env
          echo GITEA_ORG_USER=ttd >> .env
          echo POSTGRES_PASSWORD=kyeDIG@eip >> .env
          echo COMMIT= >> .env
          echo IGNORE_DOCKER_DNS_LOOKUP=true >> .env
        working-directory: src/Designer

      - name: Run setup.js script
        run: |
          node src/Designer/development/setup.js

      - name: 'Installing Dependencies'
        uses: ./.github/actions/yarn-install

      - name: Playwright run
        working-directory: src/Designer/frontend/testing/playwright
        env:
          environment: local
        run: |
          yarn setup:playwright
          yarn playwright:test:all

      - name: Store artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        if: failure()
        with:
          name: playwright-screenshots
          path: src/Designer/frontend/testing/playwright/test-results
