name: Resourceadm Playwright Tests in Dev

on:
  push:
    branches:
      - main
    paths:
      - 'src/Designer/frontend/resourceadm/**'
      - '.github/workflows/playwright-resourceadm.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright-run:
    name: 'Resourceadm Playwright Tests'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checking Out Code'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          cache: 'yarn'

      - name: Get yarn cache directory path
        working-directory: src/Designer/frontend
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Attempt to wait for deploy to environment (15 minutes sleep)
        run: |
          if [ "${{ github.run_attempt }}" != "1" ]; then
            echo "Skip waiting for deploy, since this is a re-run of the pipeline."
          else
            sleep 15m
          fi

      - name: Resourceadm Playwright run
        working-directory: src/Designer/frontend/resourceadm/testing/playwright
        env:
          PLAYWRIGHT_TEST_BASE_URL: 'https://staging.altinn.studio'
          PLAYWRIGHT_RESOURCES_ORGANIZATION: ttd
          PLAYWRIGHT_RESOURCES_REPO_NAME: ttd-resources
          PLAYWRIGHT_USER: 'AutoTest'
          PLAYWRIGHT_PASS: ${{ secrets.AUTO_TEST_USER_PWD }}
          GITEA_ACCESS_TOKEN: ${{ secrets.AUTO_TEST_USER_TOKEN_DEV }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn
          yarn install --immutable --inline-builds
          yarn playwright install --with-deps
          yarn resourceadm:playwright:test:all

      - name: Store artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        if: failure()
        with:
          name: playwright-resourceadm-screenshots
          path: src/Designer/frontend/resourceadm/testing/playwright/test-results
