name: Localtest - Build

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/Runtime/localtest/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup .NET Core SDK 8.0.x
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
        working-directory: 'src/Runtime/localtest/src/'
      - name: Build LocalTest
        run: dotnet build --configuration Debug --no-restore
        working-directory: 'src/Runtime/localtest/src/'
