name: Build and deploy Studio Components Legacy with preview

on:
  push:
    branches:
      - main
    paths:
      - 'src/Designer/frontend/libs/studio-components-legacy/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Use node LTS and yarn cache
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Storybook
        working-directory: src/Designer/frontend/libs/studio-components-legacy
        run: yarn build-storybook

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9 #v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.STUDIO_COMPONENTS_LEGACY_STATIC_WEB_APP_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/Designer/frontend/libs/studio-components-legacy/storybook-static"
          api_location: ""
          output_location: ""
